# Generated by Django 3.2.3 on 2021-05-20 17:29

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('bcc', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', django_quill.fields.QuillField()),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
    ]
