# Generated by Django 3.2.3 on 2021-05-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_mailer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailForm',
            new_name='EmailModel',
        ),
    ]
