# Generated by Django 3.2.3 on 2021-05-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_mailer', '0002_rename_emailform_emailmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailModel',
        ),
    ]
